name: CI

on:
  push:
    branches:    
      - '*'         # matches every branch
      - '!master'   # excludes master

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i yarn -g
    - run: yarn install
    - run: yarn run lint
    - run: yarn run test
    - run: yarn run build
      env:
        CI: true  